# Generated by Django 2.1.4 on 2018-12-19 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountant', '0003_applications'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='description_uk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='text_uk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title_uk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='advantages',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='advantages',
            name='text_uk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='advantages',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='advantages',
            name='title_uk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='complexservices',
            name='additionally_en',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='complexservices',
            name='additionally_uk',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='complexservices',
            name='subtitle_en',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='complexservices',
            name='subtitle_uk',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='complexservices',
            name='title_en',
            field=models.CharField(max_length=555, null=True),
        ),
        migrations.AddField(
            model_name='complexservices',
            name='title_uk',
            field=models.CharField(max_length=555, null=True),
        ),
        migrations.AddField(
            model_name='contacts',
            name='company_footer_en',
            field=models.CharField(default=None, max_length=455, null=True),
        ),
        migrations.AddField(
            model_name='contacts',
            name='company_footer_uk',
            field=models.CharField(default=None, max_length=455, null=True),
        ),
        migrations.AddField(
            model_name='contacts',
            name='street_en',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contacts',
            name='street_uk',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contacts',
            name='time_of_work_en',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contacts',
            name='time_of_work_uk',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='howwework',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='howwework',
            name='text_uk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='howwework',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='howwework',
            name='title_uk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='text_uk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='title_uk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='specialization',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='specialization',
            name='title_uk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='title',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='title',
            name='title_uk',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
