# Generated by Django 2.1.4 on 2018-12-19 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountant', '0004_auto_20181219_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='contacts',
            name='enabled',
            field=models.BooleanField(default=False, help_text='Дозволити відображати на сайті'),
        ),
        migrations.AddField(
            model_name='specialization',
            name='enabled',
            field=models.BooleanField(default=False, help_text='Дозволити відображати на сайті'),
        ),
    ]
