# Generated by Django 2.1.4 on 2018-12-19 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountant', '0005_auto_20181219_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=555)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Вид діяльності',
                'verbose_name_plural': 'Види діяльності',
            },
        ),
        migrations.AlterField(
            model_name='applications',
            name='organizational_form',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
    ]
