# Generated by Django 2.1.4 on 2018-12-19 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountant', '0006_auto_20181219_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationalForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=555)),
                ('title_en', models.CharField(max_length=555, null=True)),
                ('title_uk', models.CharField(max_length=555, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Організаційна форма',
                'verbose_name_plural': 'Організаційні форми',
            },
        ),
        migrations.CreateModel(
            name='TaxSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=555)),
                ('title_en', models.CharField(max_length=555, null=True)),
                ('title_uk', models.CharField(max_length=555, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Система опадаткування',
                'verbose_name_plural': 'Системи опадаткування',
            },
        ),
        migrations.AddField(
            model_name='activities',
            name='title_en',
            field=models.CharField(max_length=555, null=True),
        ),
        migrations.AddField(
            model_name='activities',
            name='title_uk',
            field=models.CharField(max_length=555, null=True),
        ),
        migrations.AlterField(
            model_name='applications',
            name='activity',
            field=models.CharField(blank=True, max_length=555, null=True),
        ),
        migrations.AlterField(
            model_name='applications',
            name='organizational_form',
            field=models.CharField(blank=True, max_length=555, null=True),
        ),
        migrations.AlterField(
            model_name='applications',
            name='tax_system',
            field=models.CharField(blank=True, max_length=555, null=True),
        ),
    ]
